### ISSUE TITLE
Please share with with the FreeCAD community 

### ISSUE THREAD

**Issue by luzpaz** [Brezensalzer/StepperBotLidar2#1]
https://www.forum.freecadweb.org/viewforum.php?f=24

**Comment by Brezensalzer** [comment]
Hello luzpaz,

it is beyond my capabilities to join all communities of every tool I am using.
Please feel free to post a link or copy the files to the freecad forum.

Cheers
Stefan

PS: I will publish the rest of the project on Github in the next days.

**Comment by luzpaz** [comment]
Posted at https://forum.freecadweb.org/viewtopic.php?f=24&t=29224

**Comment by Brezensalzer** [comment]
Thank You very much!
